### ISSUE TITLE
Trouble with examples

### ISSUE THREAD

**Issue by natebass** [brightdigit/Speculid#18]
**Version:** Speculid v1.0.2 [1.0.2010018057] Installed though homebrew

```speculid examples/Assets/macOS\ AppIcon.speculid``` (or any other file I tried) does not seem to generate anything, but outputs no error.

Also when I try to build the example project in xcode I get the error:
```xcodebuild: error: '/usr/local/Cellar/speculid/1.0.2/examples/../speculid.xcworkspace' does not exist.```
```Command /bin/sh failed with exit code 66```

**Comment by natebass** [comment]
@leogdion Nice project by the way. I am a noob and the readme looks very friendly. I look forward to digging into it more!

**Comment by leogdion** [comment]
Thanks @natebass. I'll definitely take a look. One of the problems I'm running into is the dependency on Inkscape. Quite frankly it's a mess. I am looking for an alternative method for converting SVG files which would make make installation much easier. That includes but is not limited to PocketSVG, SwiftSVG as well as rewriting it in JavaScript and using libraries like rsvg. 

I'll look at this particular build issue with homebrew issue and make sure I can reproduce it. Any other feedback is appreciated.

**Comment by leogdion** [comment]
Hey @natebass, I've removed Inkscape from Speculid completely in v2.0. Take a look at the [latest dev build](https://github.com/brightdigit/speculid/releases/tag/v2.0.0.010081001.299-dev) in the releases section and download the zip. 

Please note changes with v2.0 in the ReadMe:
* No Brew Install Needed
* Must recreate symbolic link or run from command line using full path.

Please let me know if you still have questions.

**Comment by leogdion** [comment]
Hey @natebass,

I'm resolving this issue for now. Take at the new home page and signup to get the latest alpha version. It's a simple drag-and-drop installation now.

Thanks,
Leo
