### ISSUE TITLE
Support other locations for inkscape and imagemagick

### ISSUE THREAD

**Issue by joshfriend** [brightdigit/speculid#7]
I have Homebrew installed with Boxen (for now), which it is located at `/opt/boxen/homebrew`. [Speculid won't be able to find inkscape or imagemagick there](https://github.com/brightdigit/speculid/blob/3e168d91d6eb246de31947f4a10063750cbca72c/framework/Models/SpeculidConfiguration.swift#L24-L25).

You could:

* Try to parse the output of `which` to locate the tools
* Read the `$HOMEBREW_ROOT` env variable to determine where homebrew is installed and go from there

**Comment by leogdion** [comment]
@joshfriend I added the ability to specify the path to each application using a `json` file. See the [README](https://github.com/brightdigit/speculid/blob/release/1.0.0/README.md#application-configuration) for more details. I also added issue #8 to added the ability to search for the executables automatically. 

Feel free to test this fix by installing the head from brew:
`brew install --HEAD speculid`
